# Generated by Django 5.2.14 on 2026-05-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('price', models.CharField(max_length=100, verbose_name='Narxi')),
                ('year', models.IntegerField(verbose_name='Yili')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
                'ordering': ['-created_at'],
            },
        ),
    ]
