# Generated by Django 5.2.12 on 2026-05-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Joylashuv'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Narxi'),
        ),
    ]
