# Generated by Django 5.2.12 on 2026-05-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_car_location_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Qo'shimcha telefon"),
        ),
    ]
