# Generated by Django 5.2.12 on 2026-05-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_car_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='following', to='app.profile', verbose_name='Obunachilar'),
        ),
    ]
