# Generated by Django 5.2.12 on 2026-05-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_message_file_message_file_type_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reaction',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Reaksiya'),
        ),
    ]
