# Generated by Django 5.2.14 on 2026-05-17 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_message_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, choices=[('qoraqalpogiston', "Qoraqalpog'iston"), ('andijon', 'Andijon'), ('buxoro', 'Buxoro'), ('jizzax', 'Jizzax'), ('qashqadaryo', 'Qashqadaryo'), ('navoiy', 'Navoiy'), ('namangan', 'Namangan'), ('samarqand', 'Samarqand'), ('surxondaryo', 'Surxondaryo'), ('sirdaryo', 'Sirdaryo'), ('toshkent', 'Toshkent viloyati'), ('fargona', "Farg'ona"), ('xorazm', 'Xorazm'), ('toshkent_sh', 'Toshkent shahri')], max_length=50, null=True, verbose_name='Viloyat'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='stories/', verbose_name='Media (rasm/video)')),
                ('is_video', models.BooleanField(default=False, verbose_name='Video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Storylar',
                'ordering': ['-created_at'],
            },
        ),
    ]
