# Generated by Django 5.2.14 on 2026-05-17 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_stories', to=settings.AUTH_USER_MODEL, verbose_name='Yoqtirganlar'),
        ),
        migrations.AddField(
            model_name='story',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_stories', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rganlar"),
        ),
    ]
