# Generated by Django 5.2.14 on 2026-05-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_story_likes_story_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='music_duration_seconds',
            field=models.IntegerField(default=30, verbose_name='Davomiylik (sekund)'),
        ),
        migrations.AddField(
            model_name='story',
            name='music_start_seconds',
            field=models.IntegerField(default=0, verbose_name='Boshlanish vaqti (sekund)'),
        ),
        migrations.AddField(
            model_name='story',
            name='spotify_preview_url',
            field=models.URLField(blank=True, null=True, verbose_name='Spotify preview URL'),
        ),
        migrations.AddField(
            model_name='story',
            name='spotify_track_artist',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Artist'),
        ),
        migrations.AddField(
            model_name='story',
            name='spotify_track_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Spotify trek ID'),
        ),
        migrations.AddField(
            model_name='story',
            name='spotify_track_image',
            field=models.URLField(blank=True, null=True, verbose_name='Album rasmi'),
        ),
        migrations.AddField(
            model_name='story',
            name='spotify_track_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Qo'shiq nomi"),
        ),
    ]
