# Generated by Django 5.2.14 on 2026-05-18 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_story_music_duration_seconds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['-created_at'], name='car_created_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['name'], name='car_name_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', 'timestamp'], name='msg_chat_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read', 'timestamp'], name='msg_notif_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-timestamp'], name='msg_time_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', '-created_at'], name='prod_user_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='prod_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='prod_created_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone'], name='prof_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['last_activity'], name='prof_online_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['region'], name='prof_region_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_verified'], name='prof_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['user', 'expires_at'], name='story_active_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-created_at'], name='story_created_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['expires_at'], name='story_expires_idx'),
        ),
    ]
