# Generated by Django 5.2.14 on 2026-05-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_car_car_created_idx_car_car_name_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='car_model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Moshina rusumi'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Narxi'),
        ),
    ]
