# Generated by Django 5.2.14 on 2026-05-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_car_model_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mileage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Probeg'),
        ),
    ]
