# Generated by Django 5.2.14 on 2026-05-19 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_product_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Fayl nomi')),
                ('file_size', models.CharField(max_length=50, verbose_name='Fayl hajmi')),
                ('platform', models.CharField(max_length=50, verbose_name='Platforma')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklab olingan vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuklab olish tarixi',
                'verbose_name_plural': 'Yuklab olish tarixi',
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['-downloaded_at'], name='dload_time_idx'), models.Index(fields=['user'], name='dload_user_idx')],
            },
        ),
    ]
