# Generated by Django 5.2.14 on 2026-05-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_downloadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='from_sell_form',
            field=models.BooleanField(default=False, verbose_name='Sotish formasi orqali'),
        ),
        migrations.AddField(
            model_name='product',
            name='from_sell_form',
            field=models.BooleanField(default=False, verbose_name='Sotish formasi orqali'),
        ),
    ]
