# Generated by Django 5.2.14 on 2026-05-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yili'),
        ),
    ]
