T = {
    # Navigation
    'home': 'Home',
    'add': 'Add',
    'story': 'Story',
    'profile': 'Profile',
    'login': 'Login',
    'logout': 'Logout',
    'register': 'Register',
    'search': 'Search',
    'sell': 'Sell',
    'chat': 'Send SMS',
    'write': 'Write',
    'no_chats': 'No messages',
    'no_notifs': 'No notifications',
    'chats': 'Messages',
    'notifications': 'Notifications',
    'loading': 'Loading...',
    'search_placeholder': 'Search profile or car...',
    'search_profile': 'Search profile...',
    'search_product': 'Search product...',
    'add_product': 'Add product',
    'profile_search': 'Search profile or car...',

    # Footer
    'brand': 'avtosotuv.uz',
    'for_advertisers': 'For advertisers',
    'mobile_version': 'Mobile version',
    'uz_news': 'Uzbekistan news',
    'kz_news': 'Kazakhstan news',
    'write_admin': 'Write to admin',
    'personal_cabinet': 'Personal cabinet',
    'ad_rules': 'Ad rules',
    'social_media': 'Social media',

    # Auth
    'login_title': 'Login',
    'login_subtitle': 'Enter your nickname and password',
    'nickname': 'Nickname',
    'nickname_placeholder': 'Your nickname',
    'password': 'Password',
    'password_placeholder': 'Your password',
    'forgot_password': 'Forgot password',
    'no_account': 'No account?',
    'register_title': 'Register',
    'register_subtitle': 'Enter your details to create an account',
    'email': 'Gmail',
    'email_placeholder': 'example@gmail.com',
    'phone': 'Phone',
    'phone_placeholder': '+998 (__) ___-__-__',
    'confirm_password': 'Confirm password',
    'confirm_password_placeholder': 'Enter password again',
    'profile_picture': 'Profile picture',
    'choose_image': 'Choose image',
    'region': 'Region',
    'select_region': 'Select region',
    'have_account': 'Have an account?',

    # Verify
    'verify_title': 'Verify SMS code',
    'verify_heading': 'Enter SMS code',
    'verify_subtitle': 'Enter the 6-digit code sent to your phone',
    'test_code': 'Test code:',
    'test_code_note': 'After SMS service is connected, this code will arrive via SMS',
    'confirm': 'Confirm',
    'send': 'Send',

    # Home
    'products': 'Products',
    'no_products': 'No products yet',
    'gallery': 'Choose from gallery',
    'cancel': 'Cancel',
    'post_story': 'Post to Story',
    'add_music': '🎵 Add music',
    'change_music': '🎵 Change music',
    'spotify_search': 'Search from Spotify...',
    'start_time': 'Start time',
    'min_sec': 'min : sec',
    'select': 'Select',
    'likers': 'Likes',
    'close': 'Close',
    'no_results': 'Nothing found',
    'error': 'Error!',
    'like_count': 'Likes',

    # Profile
    'subscribers': 'Subscribers',
    'following': 'Following',
    'edit_profile': 'Edit profile',
    'add_story': 'Add Story',
    'unsubscribe': 'Unsubscribe',
    'subscribe': 'Subscribe',
    'admin_products': 'Admin products',
    'edit': 'Edit',
    'delete': 'Delete',
    'confirm_delete': 'Are you sure you want to delete?',
    'back': 'Back',

    # Edit Profile
    'edit_profile_title': 'Edit profile',
    'change_photo': 'Change photo',
    'first_name': 'First name',
    'first_name_placeholder': 'Your name',
    'old_password': 'Old password',
    'old_password_placeholder': 'Your old password',
    'new_password': 'New password (if you want to change)',
    'new_password_placeholder': 'New password',
    'save': 'Save',

    # Search
    'search_title': 'Search',
    'search_none': 'Nothing found',
    'profiles': 'Profiles',

    # Download
    'download_history': 'Download history',
    'redownload': 'Redownload',
    'no_downloads': 'Nothing downloaded',
    'no_downloads_desc': 'App not downloaded yet. Download using the button below.',
    'download': 'Download',

    # Subscribers
    'no_users': 'No users found',

    # Ads
    'ads': 'Ads',
    'add_ad': 'Add new ad',
    'edit_ad': 'Edit ad',
    'delete_ad': 'Delete ad',
    'name': 'Name',
    'car_name': 'Car name',
    'phone_label': 'Phone *',
    'phone_placeholder': '+998 (xx) xxx xx-xx',
    'extra_phone': 'Extra phone',
    'location_image': 'Location image',
    'location': 'Location',
    'location_placeholder': 'Enter address or coordinates or click on map',
    'all_ads': 'All ads',
    'no_ads': 'No ads yet',
    'location_not_found': 'Location not found!',

    # Product Add
    'add_product_title': 'Add new product',
    'edit_product_title': 'Edit product',
    'car_model': 'Car model *',
    'car_model_placeholder': 'e.g. Nexia 3, Damas, Malibu',
    'price': 'Price',
    'price_placeholder': 'e.g. 15000 sum',
    'mileage': 'Mileage',
    'mileage_placeholder': 'e.g. 150000 km',
    'paint': 'Paint job?',
    'paint_placeholder': 'Yes / No',
    'description': 'Description',
    'description_placeholder': 'Additional info...',
    'image': 'Image *',
    'current_image': 'Current image:',
    'submit_add': 'Add',

    # Chat
    'calling': 'Calling...',
    'call_ended': 'Call ended',
    'recording': 'Recording...',
    'record': 'Record',
    'stop': 'Stop',
    'send_msg': 'Send',
    'online': 'online',
    'last_seen': 'last seen',
    'never_logged': 'Never logged in',
    'silent_call': 'Silent call',
    'video_call': 'Video call',
    'audio_call': 'Audio call',
    'react': 'React',
    'message_placeholder': 'Write a message...',
    'video_msg': 'Video message',
    'voice_msg': 'Voice message',
    'no_messages': 'No messages yet',
    'accept': 'Accept',
    'reject': 'Reject',
    'reply': 'Reply',
    'reply_placeholder': 'Write a reply...',

    # App Banner
    'in_app_faster': 'In the app -- faster and more convenient',
    'scan_qr': 'Scan QR code to download',
    'download_app': 'Download avtosotuv.uz app',
    'choose_platform': 'Choose your phone platform',
    'google_play': 'Google Play',
    'app_store': 'App Store',
    'or': 'or',
    'download_apk': 'Download APK',
    'mb': 'MB',
    'app_development': 'App is under development. Coming soon!',

    # Messages
    'sms_verified': 'Phone verified! Welcome!',
    'wrong_code': 'Wrong code! Try again.',
    'welcome': 'Welcome',
    'wrong_credentials': 'Wrong nickname or password!',
    'nickname_taken': 'This nickname is taken!',
    'registered': 'Registered! Enter SMS code.',
    'car_model_required': 'Car model and image are required!',
    'product_added': 'Product added!',
    'product_edited': 'Product edited!',
    'ad_added': 'Ad added!',
    'ad_edited': 'Ad edited!',
    'ad_deleted': 'Ad deleted!',
    'profile_updated': 'Profile updated!',
    'old_password_required': 'Enter old password!',
    'wrong_old_password': 'Wrong old password!',
    'file_not_found': 'File not found',

    # Language
    'language': 'Language',
    'uzbek': "O'zbek",
    'russian': 'Русский',
    'english': 'English',

    # Region filter
    'all_regions': 'All regions',
}
