T = {
    # Navigation
    'home': 'Bosh sahifa',
    'add': "Qo'shish",
    'story': 'Story',
    'profile': 'Profil',
    'login': 'Kirish',
    'logout': 'Chiqish',
    'register': "Ro'yxatdan o'tish",
    'search': 'Qidirish',
    'sell': 'Sotish',
    'chat': 'SMS yozish',
    'write': 'Javob yozish',
    'no_chats': "Xabarlar yo'q",
    'no_notifs': "Yangi bildirishnomalar yo'q",
    'chats': 'Xabarlar',
    'notifications': 'Bildirishnomalar',
    'loading': 'Yuklanmoqda...',
    'search_placeholder': 'Profil yoki moshina qidirish...',
    'search_profile': 'Profil qidirish...',
    'search_product': 'Mahsulot qidirish...',
    'add_product': 'Mahsulot qo\'shish',
    'profile_search': 'Profil yoki moshina qidirish...',

    # Footer
    'brand': 'avtosotuv.uz',
    'for_advertisers': 'Reklama beruvchilarga',
    'mobile_version': 'Mobil versiya',
    'uz_news': "O'zbekiston yangiliklari",
    'kz_news': "Qozog'iston yangiliklari",
    'write_admin': 'Admin ga yozing',
    'personal_cabinet': 'Shaxsiy kabinet',
    'ad_rules': "E'lon qoidalari",
    'social_media': 'Ijtimoiy tarmoqlar',

    # Auth
    'login_title': 'Kirish',
    'login_subtitle': 'Nik-name va parolingizni kiriting',
    'nickname': 'Nik-name',
    'nickname_placeholder': 'Nik-namingiz',
    'password': 'Parol',
    'password_placeholder': 'Parolingiz',
    'forgot_password': 'Parolim esdan chiqdi',
    'no_account': 'Hisobingiz yo\'qmi?',
    'register_title': "Ro'yxatdan o'tish",
    'register_subtitle': 'Hisob yaratish uchun ma\'lumotlaringizni kiriting',
    'email': 'Gmail',
    'email_placeholder': 'example@gmail.com',
    'phone': 'Telefon',
    'phone_placeholder': '+998 (__) ___-__-__',
    'confirm_password': 'Parolni takrorlang',
    'confirm_password_placeholder': 'Parolni qayta kiriting',
    'profile_picture': 'Profil rasmi',
    'choose_image': 'Rasm tanlash',
    'region': 'Viloyat',
    'select_region': 'Viloyatni tanlang',
    'have_account': 'Hisobingiz bormi?',

    # Verify
    'verify_title': 'SMS kodni tasdiqlash',
    'verify_heading': 'SMS kodni kiriting',
    'verify_subtitle': 'Telefoningizga yuborilgan 6 xonali kodni yozing',
    'test_code': 'Test kodi:',
    'test_code_note': 'SMS xizmati ulangandan keyin bu kod telefonga keladi',
    'confirm': 'Tasdiqlash',
    'send': 'Yuborish',

    # Home
    'products': 'Mahsulotlar',
    'no_products': 'Hozircha mahsulotlar yo\'q',
    'gallery': 'Galereyadan tanlash',
    'cancel': 'Bekor qilish',
    'post_story': 'Storyga qo\'yish',
    'add_music': '🎵 Musiqa qo\'shish',
    'change_music': '🎵 Musiqani o\'zgartirish',
    'spotify_search': 'Spotify dan qidirish...',
    'start_time': 'Boshlanish vaqti',
    'min_sec': 'daqiqa : soniya',
    'select': 'Tanlash',
    'likers': 'Yoqtirganlar',
    'close': 'Yopish',
    'no_results': 'Hech narsa topilmadi',
    'error': 'Xatolik yuz berdi!',
    'like_count': 'Yoqtirganlar',

    # Profile
    'subscribers': 'Obunachilar',
    'following': 'Obunalar',
    'edit_profile': 'Profilni tahrirlash',
    'add_story': 'Story qo\'shish',
    'unsubscribe': 'Obunani bekor qilish',
    'subscribe': 'Obuna bo\'lish',
    'admin_products': 'Admin mahsulotlari',
    'edit': 'Tahrirlash',
    'delete': "O'chirish",
    'confirm_delete': 'Rostdan ham o\'chirmoqchimisiz?',
    'back': 'Ortga',

    # Edit Profile
    'edit_profile_title': 'Profilni tahrirlash',
    'change_photo': 'Rasmni o\'zgartirish',
    'first_name': 'Ism',
    'first_name_placeholder': 'Ismingiz',
    'old_password': 'Eski parol',
    'old_password_placeholder': 'Eski parolingiz',
    'new_password': 'Yangi parol (agar o\'zgartirmoqchi bo\'lsangiz)',
    'new_password_placeholder': 'Yangi parol',
    'save': 'Saqlash',
    'delete_story': "Storyni ochirishni xohlaysizmi?",

    # Search
    'search_title': 'Qidiruv',
    'search_none': 'Hech narsa topilmadi',
    'profiles': 'Profil',

    # Download
    'download_history': 'Yuklab olishlar tarixi',
    'redownload': 'Qayta yuklash',
    'no_downloads': 'Hech narsa yuklanmagan',
    'no_downloads_desc': 'Ilova hali yuklab olinmagan. Pastdagi tugma orqali yuklab oling.',
    'download': 'Yuklab olish',

    # Subscribers
    'no_users': 'Hech kim topilmadi',

    # Ads
    'ads': 'Reklamalar',
    'add_ad': 'Yangi reklama qo\'shish',
    'edit_ad': 'Reklamani tahrirlash',
    'delete_ad': 'Reklamani o\'chirish',
    'name': 'Nomi',
    'car_name': 'Mashina nomi',
    'phone_label': 'Telefon *',
    'phone_placeholder': '+998 (xx) xxx xx-xx',
    'extra_phone': "Qo'shimcha telefon",
    'location_image': 'Joylashuvdagi rasm',
    'location': 'Joylashuv',
    'location_placeholder': 'Manzil yoki koordinata yozing yoki xaritadan bosing',
    'all_ads': 'Barcha reklamalar',
    'no_ads': "Hozircha reklamalar yo'q",
    'location_not_found': 'Joylashuv topilmadi!',

    # Product Add
    'add_product_title': 'Yangi mahsulot qo\'shish',
    'edit_product_title': 'Mahsulotni tahrirlash',
    'car_model': 'Moshina rusumi *',
    'car_model_placeholder': 'Mas: Nexia 3, Damas, Malibu',
    'price': 'Narxi',
    'price_placeholder': 'Mas: 15000 so\'m',
    'mileage': 'Probeg',
    'mileage_placeholder': 'Mas: 150000 km',
    'paint': 'Kraska sepilganmi?',
    'paint_placeholder': 'Ha / Yo\'q',
    'description': 'Tavsif',
    'description_placeholder': "Qo'shimcha ma'lumot...",
    'image': 'Rasm *',
    'current_image': 'Joriy rasm:',
    'submit_add': "Qo'shish",

    # Chat
    'calling': "Qo'ng'iroq qilish...",
    'call_ended': "Qo'ng'iroq tugadi",
    'recording': 'Yozib olish...',
    'record': 'Yozish',
    'stop': "To'xtatish",
    'send_msg': 'Jonatish',
    'online': 'online',
    'last_seen': 'da chiqib ketgan',
    'never_logged': 'Hech qachon kirmagan',
    'silent_call': 'Ovozsiz qo\'ng\'iroq',
    'video_call': 'Video qo\'ng\'iroq',
    'audio_call': 'Audio qo\'ng\'iroq',
    'react': 'Munosabat bildirish',
    'message_placeholder': 'Xabar yozish...',
    'video_msg': 'Video xabar',
    'voice_msg': 'Ovozli xabar',
    'no_messages': 'Hozircha xabarlar yo\'q',
    'accept': 'Qabul qilish',
    'reject': 'Rad etish',
    'reply': 'Javob',
    'reply_placeholder': 'Javob yozish...',

    # App Banner
    'in_app_faster': 'Ilovada -- tezroq va qulayroq',
    'scan_qr': 'Yuklab olish uchun QR kodni skanerlang',
    'download_app': 'avtosotuv.uz ilovasini yuklab olish',
    'choose_platform': 'Telefoningizga mos platformani tanlang',
    'google_play': 'Google Play',
    'app_store': 'App Store',
    'or': 'yoki',
    'download_apk': 'APK ni yuklab olish',
    'mb': 'MB',
    'app_development': 'Ilova hozirda ishlab chiqilmoqda. Tez kunda tayyor bo\'ladi!',

    # Verify
    'sms_verified': 'Telefon tasdiqlandi! Xush kelibsiz!',
    'wrong_code': "Noto'g'ri kod! Qayta urinib ko'ring.",
    'welcome': 'Xush kelibsiz',
    'wrong_credentials': "Nik-name yoki parol noto'g'ri!",
    'nickname_taken': 'Bu nik-name band!',
    'registered': "Ro'yxatdan o'tdingiz! SMS kodni kiriting.",
    'car_model_required': 'Moshina rusumi va rasm majburiy!',
    'product_added': "Mahsulot qo'shildi!",
    'product_edited': 'Mahsulot tahrirlandi!',
    'ad_added': "Reklama qo'shildi!",
    'ad_edited': 'Reklama tahrirlandi!',
    'ad_deleted': "Reklama o'chirildi!",
    'profile_updated': 'Profil yangilandi!',
    'old_password_required': 'Eski parolni kiriting!',
    'wrong_old_password': "Eski parol noto'g'ri!",
    'file_not_found': 'Fayl topilmadi',

    # Language
    'language': 'Til',
    'uzbek': "O'zbek",
    'russian': 'Русский',
    'english': 'English',

    # Region filter
    'all_regions': 'Hamma viloyatlar',
}
