T = {
    # Navigation
    'home': 'Главная',
    'add': 'Добавить',
    'story': 'История',
    'profile': 'Профиль',
    'login': 'Вход',
    'logout': 'Выход',
    'register': 'Регистрация',
    'search': 'Поиск',
    'sell': 'Продать',
    'chat': 'Написать SMS',
    'write': 'Написать',
    'no_chats': 'Нет сообщений',
    'no_notifs': 'Нет уведомлений',
    'chats': 'Сообщения',
    'notifications': 'Уведомления',
    'loading': 'Загрузка...',
    'search_placeholder': 'Поиск профиля или машины...',
    'search_profile': 'Поиск профиля...',
    'search_product': 'Поиск товара...',
    'add_product': 'Добавить товар',
    'profile_search': 'Поиск профиля или машины...',

    # Footer
    'brand': 'avtosotuv.uz',
    'for_advertisers': 'Рекламодателям',
    'mobile_version': 'Мобильная версия',
    'uz_news': 'Новости Узбекистана',
    'kz_news': 'Новости Казахстана',
    'write_admin': 'Написать админу',
    'personal_cabinet': 'Личный кабинет',
    'ad_rules': 'Правила объявлений',
    'social_media': 'Социальные сети',

    # Auth
    'login_title': 'Вход',
    'login_subtitle': 'Введите ник-нейм и пароль',
    'nickname': 'Ник-нейм',
    'nickname_placeholder': 'Ваш ник-нейм',
    'password': 'Пароль',
    'password_placeholder': 'Ваш пароль',
    'forgot_password': 'Забыл пароль',
    'no_account': 'Нет аккаунта?',
    'register_title': 'Регистрация',
    'register_subtitle': 'Введите данные для создания аккаунта',
    'email': 'Gmail',
    'email_placeholder': 'example@gmail.com',
    'phone': 'Телефон',
    'phone_placeholder': '+998 (__) ___-__-__',
    'confirm_password': 'Повторите пароль',
    'confirm_password_placeholder': 'Введите пароль ещё раз',
    'profile_picture': 'Фото профиля',
    'choose_image': 'Выбрать фото',
    'region': 'Регион',
    'select_region': 'Выберите регион',
    'have_account': 'Есть аккаунт?',

    # Verify
    'verify_title': 'Подтверждение SMS кода',
    'verify_heading': 'Введите SMS код',
    'verify_subtitle': 'Введите 6-значный код, отправленный на ваш телефон',
    'test_code': 'Тестовый код:',
    'test_code_note': 'После подключения SMS этот код придёт на телефон',
    'confirm': 'Подтвердить',
    'send': 'Отправить',

    # Home
    'products': 'Товары',
    'no_products': 'Пока нет товаров',
    'gallery': 'Выбрать из галереи',
    'cancel': 'Отмена',
    'post_story': 'Опубликовать в Story',
    'add_music': '🎵 Добавить музыку',
    'change_music': '🎵 Изменить музыку',
    'spotify_search': 'Поиск в Spotify...',
    'start_time': 'Время начала',
    'min_sec': 'минут : секунд',
    'select': 'Выбрать',
    'likers': 'Лайки',
    'close': 'Закрыть',
    'no_results': 'Ничего не найдено',
    'error': 'Ошибка!',
    'like_count': 'Оценили',

    # Profile
    'subscribers': 'Подписчики',
    'following': 'Подписки',
    'edit_profile': 'Редактировать профиль',
    'add_story': 'Добавить Story',
    'unsubscribe': 'Отписаться',
    'subscribe': 'Подписаться',
    'admin_products': 'Товары администратора',
    'edit': 'Редактировать',
    'delete': 'Удалить',
    'confirm_delete': 'Вы уверены, что хотите удалить?',
    'back': 'Назад',

    # Edit Profile
    'edit_profile_title': 'Редактировать профиль',
    'change_photo': 'Изменить фото',
    'first_name': 'Имя',
    'first_name_placeholder': 'Ваше имя',
    'old_password': 'Старый пароль',
    'old_password_placeholder': 'Ваш старый пароль',
    'new_password': 'Новый пароль (если хотите изменить)',
    'new_password_placeholder': 'Новый пароль',
    'save': 'Сохранить',
    'delete_story': 'Удалить эту историю?',

    # Search
    'search_title': 'Поиск',
    'search_none': 'Ничего не найдено',
    'profiles': 'Профиль',

    # Download
    'download_history': 'История загрузок',
    'redownload': 'Перезагрузить',
    'no_downloads': 'Ничего не загружено',
    'no_downloads_desc': 'Приложение ещё не загружено. Загрузите через кнопку ниже.',
    'download': 'Скачать',

    # Subscribers
    'no_users': 'Никого нет',

    # Ads
    'ads': 'Объявления',
    'add_ad': 'Добавить объявление',
    'edit_ad': 'Редактировать объявление',
    'delete_ad': 'Удалить объявление',
    'name': 'Название',
    'car_name': 'Название машины',
    'phone_label': 'Телефон *',
    'phone_placeholder': '+998 (xx) xxx xx-xx',
    'extra_phone': 'Доп. телефон',
    'location_image': 'Фото местоположения',
    'location': 'Местоположение',
    'location_placeholder': 'Введите адрес или координаты или нажмите на карту',
    'all_ads': 'Все объявления',
    'no_ads': 'Пока нет объявлений',
    'location_not_found': 'Местоположение не найдено!',

    # Product Add
    'add_product_title': 'Добавить товар',
    'edit_product_title': 'Редактировать товар',
    'car_model': 'Модель машины *',
    'car_model_placeholder': 'Напр: Nexia 3, Damas, Malibu',
    'price': 'Цена',
    'price_placeholder': 'Напр: 15000 сум',
    'mileage': 'Пробег',
    'mileage_placeholder': 'Напр: 150000 км',
    'paint': 'Покрашена?',
    'paint_placeholder': 'Да / Нет',
    'description': 'Описание',
    'description_placeholder': 'Дополнительная информация...',
    'image': 'Фото *',
    'current_image': 'Текущее фото:',
    'submit_add': 'Добавить',

    # Chat
    'calling': 'Звонок...',
    'call_ended': 'Звонок завершён',
    'recording': 'Запись...',
    'record': 'Записать',
    'stop': 'Стоп',
    'send_msg': 'Отправить',
    'online': 'онлайн',
    'last_seen': 'был(а) в',
    'never_logged': 'Никогда не заходил(а)',
    'silent_call': 'Тихий звонок',
    'video_call': 'Видеозвонок',
    'audio_call': 'Аудиозвонок',
    'react': 'Реакция',
    'message_placeholder': 'Написать сообщение...',
    'video_msg': 'Видеосообщение',
    'voice_msg': 'Голосовое сообщение',
    'no_messages': 'Пока нет сообщений',
    'accept': 'Принять',
    'reject': 'Отклонить',
    'reply': 'Ответить',
    'reply_placeholder': 'Написать ответ...',

    # App Banner
    'in_app_faster': 'В приложении -- быстрее и удобнее',
    'scan_qr': 'Сканируйте QR код для загрузки',
    'download_app': 'Скачать приложение avtosotuv.uz',
    'choose_platform': 'Выберите платформу для вашего телефона',
    'google_play': 'Google Play',
    'app_store': 'App Store',
    'or': 'или',
    'download_apk': 'Скачать APK',
    'mb': 'МБ',
    'app_development': 'Приложение в разработке. Скоро будет готово!',

    # Messages
    'sms_verified': 'Телефон подтверждён! Добро пожаловать!',
    'wrong_code': 'Неверный код! Попробуйте снова.',
    'welcome': 'Добро пожаловать',
    'wrong_credentials': 'Неверный ник-нейм или пароль!',
    'nickname_taken': 'Этот ник-нейм занят!',
    'registered': 'Вы зарегистрированы! Введите SMS код.',
    'car_model_required': 'Модель машины и фото обязательны!',
    'product_added': 'Товар добавлен!',
    'product_edited': 'Товар изменён!',
    'ad_added': 'Объявление добавлено!',
    'ad_edited': 'Объявление изменено!',
    'ad_deleted': 'Объявление удалено!',
    'profile_updated': 'Профиль обновлён!',
    'old_password_required': 'Введите старый пароль!',
    'wrong_old_password': 'Неверный старый пароль!',
    'file_not_found': 'Файл не найден',

    # Language
    'language': 'Язык',
    'uzbek': "O'zbek",
    'russian': 'Русский',
    'english': 'English',

    # Region filter
    'all_regions': 'Все регионы',
}
